Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 12
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/AbcSize:
  Max: 50
AllCops:
  NewCops: enable
  SuggestExtensions: false
